version: '3'
services:
  main:
    build: .
    command: npm start
    image: hoi15a/discord-bot
    deploy:
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 5
        window: 10s
